[package]
name = "tuicher-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = "2.0.1"
dirs = "6.0.0"
log = "0.4.28"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
